--Lab 7

--Kosta Nikopoulos

--DROP TABLE games;
--DROP TABLE store;
--DROP SEQUENCE seq_generate_pk;

--Sequence
CREATE SEQUENCE seq_generate_pk
START WITH 500
INCREMENT BY 100
MAXVALUE 3000;


CREATE TABLE games(
g_id NUMBER NOT NULL PRIMARY KEY,
g_name VARCHAR2(20) NOT NULL,
g_price NUMBER(8,3) NOT NULL,
g_quantity NUMBER NOT NULL,
release_date DATE NOT NULL
);

CREATE TABLE store(
s_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 500 INCREMENT BY 100
NOT NULL PRIMARY KEY,
s_name VARCHAR2(25) NOT NULL,
s_location VARCHAR2(50) NOT NULL,
s_quantity NUMBER NOT NULL,
s_contact CHAR(12) NOT NULL,
g_id NUMBER,

CONSTRAINT fk_store_games
FOREIGN KEY(g_id)REFERENCES games(g_id));

--Games
INSERT INTO games (g_id, g_name, g_price, g_quantity, release_date)
VALUES (seq_generate_pk.NEXTVAL, 'Assassins Creed', 40, 9000, DATE '2007-06-25');
--Store
INSERT INTO store (s_name, s_location, s_quantity, s_contact, g_id)
VALUES ('Walmart','Laval', 100, '450-969-3226', seq_generate_pk.CURRVAL);
--Games
INSERT INTO games (g_id, g_name, g_price, g_quantity, release_date)
VALUES (seq_generate_pk.NEXTVAL, 'Transformers', 30, 5000, DATE '2009-08-30');
--Store
INSERT INTO store (s_name, s_location, s_quantity, s_contact, g_id)
VALUES ('EB Games','Chateaugay', 500, '450-699-9011',seq_generate_pk.CURRVAL );
--Games
INSERT INTO games (g_id, g_name, g_price, g_quantity, release_date)
VALUES (seq_generate_pk.NEXTVAL, 'Minecraft', 35, 2000, DATE '2011-11-18');
--Store
INSERT INTO store (s_name, s_location, s_quantity, s_contact, g_id)
VALUES ('Best Buy', 'Laval', 200, '450-781-2030', seq_generate_pk.CURRVAL);
--Games
INSERT INTO games (g_id, g_name, g_price, g_quantity, release_date)
VALUES (seq_generate_pk.NEXTVAL, 'Fortnite', 29.99, 6000, DATE '2017-07-21');
--Store
INSERT INTO store (s_name, s_location, s_quantity, s_contact, g_id)
VALUES ('La Source','Montreal', 300, '450-689-7905', seq_generate_pk.CURRVAL);
--Games
INSERT INTO games (g_id, g_name, g_price, g_quantity, release_date)
VALUES (seq_generate_pk.NEXTVAL, 'CallofDuty', 99.99, 7000, DATE '2020-11-19');
--Store
INSERT INTO store (s_name, s_location, s_quantity, s_contact, g_id)
VALUES ('Walmart','Montreal', 400, '514-832-4810', seq_generate_pk.CURRVAL);